name: Build and Deploy Jekyll Site
on:
  push:
    branches: [ main ]
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build Jekyll
        uses: jekyll/builder@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
    environment:
      name: github-pages

